processing_nodes:
  count: 10

api:
  bind: 0.0.0.0:8080

gateways:
  mygateway:
    listeners:
      - bind: 192.168.1.31:19132
        receive_proxy_protocol: true
      - bind: 192.168.1.21:19132
    servers:
      - myserver
    server_not_found_message: Sorry {{username}}, but {{serverAddress}} was not found

servers:
  myserver:
    domains:
      - 192.168.1.31
      - 192.168.1.21
    address: example.com:19132
    send_proxy_protocol: false
    webhooks:
      - mywebhook

webhooks:
  mywebhook:
    url: https://mc.example.com/callback
    events:
      - PlayerJoin
      - PlayerLeave

defaults:
  gateway:
    listener:
      receive_proxy_protocol: false
      receive_real_ip: false
      ping_status:
        edition: MCPE
        protocol_version: 471
        version_name: "1.17.41"
        player_count: 0
        max_player_count: 10
        game_mode: SURVIVAL
        game_mode_numeric: 1
        motd: |
          BedProx
          Join!
  server:
    proxy_bind: 0.0.0.0
    dial_timeout: 1s
    dial_timeout_message: Sorry {{username}}, but the server is currently unreachable
  webhook:
    client_timeout: 1s
